In [1]:
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
serviceAreas_df = pd.DataFrame(pd.read_csv("MSSA_Detail.csv"))
serviceAreas_df.head()

,OBJECTID,TRACT,STATE_FIPS,CNTY_FIPS,TRACT_CODE,CENSUS_KEY,COUNTY,TRACT_ID,MSSA_ID,MSSA_NAME,...,AGE_18_64,PCT_18_64,AGE_65OVER,PCT_65OVER,ELD_RATIO,YTH_RATIO,Shape_STArea_1,Shape_STLength_1,Shape__Area,Shape__Length
0,1,4427.0,6,1,442700,6001442700,Alameda,4427.0,2i,Fremont South/Mission San Jose/Newark South/Wa...,...,1920,60.797973,491,15.547815,0.085366,0.182927,0,0,1.234033e+06,4764.916655
1,2,4428.0,6,1,442800,6001442800,Alameda,4428.0,2i,Fremont South/Mission San Jose/Newark South/Wa...,...,2035,65.245271,419,13.433793,0.296117,0.475728,0,0,1.278647e+06,4762.049318
2,3,2049.2,6,37,204920,6037204920,Los Angeles,2049.2,78.2h,Boyle Heights Central/City Terrace West,...,1580,61.936495,272,10.662485,0.209726,0.924012,0,0,9.099753e+05,3900.202320
3,4,2051.1,6,37,205110,6037205110,Los Angeles,2051.1,78.2h,Boyle Heights Central/City Terrace West,...,2097,58.970754,168,4.724409,0.138821,0.888206,0,0,2.869607e+05,2813.128371
4,5,2051.2,6,37,205120,6037205120,Los Angeles,2051.2,78.2h,Boyle Heights Central/City Terrace West,...,2154,61.666190,286,8.187804,0.286744,0.670029,0,0,1.466126e+06,6115.674007

In [5]:
serviceAreas_df.drop(columns=['OBJECTID', 'STATE_FIPS'])
serviceAreas_df.dropna(inplace=True)

8036