In [35]:
import matplotlib.pyplot as plt
import pandas as pd

In [44]:
serviceAreas_df = pd.DataFrame(pd.read_csv("MSSA_Detail.csv"))
serviceAreas_df.head()

,OBJECTID,TRACT,STATE_FIPS,CNTY_FIPS,TRACT_CODE,CENSUS_KEY,COUNTY,TRACT_ID,MSSA_ID,MSSA_NAME,...,AGE_18_64,PCT_18_64,AGE_65OVER,PCT_65OVER,ELD_RATIO,YTH_RATIO,Shape_STArea_1,Shape_STLength_1,Shape__Area,Shape__Length
0,1,4427.0,6,1,442700,6001442700,Alameda,4427.0,2i,Fremont South/Mission San Jose/Newark South/Wa...,...,1920,60.797973,491,15.547815,0.085366,0.182927,0,0,1.234033e+06,4764.916655
1,2,4428.0,6,1,442800,6001442800,Alameda,4428.0,2i,Fremont South/Mission San Jose/Newark South/Wa...,...,2035,65.245271,419,13.433793,0.296117,0.475728,0,0,1.278647e+06,4762.049318
2,3,2049.2,6,37,204920,6037204920,Los Angeles,2049.2,78.2h,Boyle Heights Central/City Terrace West,...,1580,61.936495,272,10.662485,0.209726,0.924012,0,0,9.099753e+05,3900.202320
3,4,2051.1,6,37,205110,6037205110,Los Angeles,2051.1,78.2h,Boyle Heights Central/City Terrace West,...,2097,58.970754,168,4.724409,0.138821,0.888206,0,0,2.869607e+05,2813.128371
4,5,2051.2,6,37,205120,6037205120,Los Angeles,2051.2,78.2h,Boyle Heights Central/City Terrace West,...,2154,61.666190,286,8.187804,0.286744,0.670029,0,0,1.466126e+06,6115.674007

In [45]:
serviceAreas_df.drop(columns=['OBJECTID', 'STATE_FIPS', 'MSSA_ID', 'TRACT_ID', 'TRACT_CODE', 'TRACT', 'CENSUS_KEY', 'COUNTY',
                             'MSSA_NAME', 'Shape_STArea_1', 'Shape_STLength_1', 'Shape__Area', 'Shape__Length'], inplace=True)
serviceAreas_df.dropna(inplace=True)

serviceAreas_df.head()

,CNTY_FIPS,AREA_SQMI,POP,POP_CIV,TOTALPOVPOP,POP100POV,PCT100POV,POP200POV,PCT200POV,WHITE,...,AGE_UNDER5,PCT_UNDER5,AGE_UNDR18,PCT_UNDR18,AGE_18_64,PCT_18_64,AGE_65OVER,PCT_65OVER,ELD_RATIO,YTH_RATIO
0,1,0.476463,2459,3158,3158,104,3.3,217,6.871438,1774,...,169,5.533726,747,23.654212,1920,60.797973,491,15.547815,0.085366,0.182927
1,1,0.493688,2396,3119,3119,365,11.7,874,28.021802,1508,...,159,5.773420,665,21.320936,2035,65.245271,419,13.433793,0.296117,0.475728
2,37,0.351343,103,2551,2551,702,27.5,1602,62.798902,1702,...,90,4.867496,699,27.401019,1580,61.936495,272,10.662485,0.209726,0.924012
3,37,0.110796,148,3556,3556,1650,46.4,2939,82.649044,1878,...,145,7.607555,1291,36.304837,2097,58.970754,168,4.724409,0.138821,0.888206
4,37,0.566074,146,3493,3493,1358,38.9,2717,77.784140,1754,...,122,5.714286,1053,30.146006,2154,61.666190,286,8.187804,0.286744,0.670029

In [46]:
serviceAreas_df.columns

Index(['CNTY_FIPS', 'AREA_SQMI', 'POP', 'POP_CIV', 'TOTALPOVPOP', 'POP100POV',
       'PCT100POV', 'POP200POV', 'PCT200POV', 'WHITE', 'PCT_WHITE',
       'NHS_WHITE', 'PCT_NHS_WHITE', 'BLACK', 'PCT_BLACK', 'NHS_BLACK',
       'PCT_NHS_BLACK', 'ASIAN', 'PCT_ASIAN', 'NHS_ASIAN', 'PCT_NHS_ASIAN',
       'AMIND_ESK', 'PCT_AMIND_ESK', 'NHS_AMIND_ESK', 'PCT_NHS_AMIND_ESK',
       'ISLANDER', 'PCT_ISLAND', 'NHS_ISLANDER', 'PCT_NHS_ISLANDER',
       'OTHER_RACE', 'PCT_OTHER', 'NHS_OTHER_RACE', 'PCT_NHS_OTHER_RACE',
       'MULTI_RACE', 'PCT_MULTI', 'NHS_MULTI_RACE', 'PCT_NHS_MULTI_RACE',
       'HISPANIC', 'PCT_HSPNC', 'AGE_UNDER5', 'PCT_UNDER5', 'AGE_UNDR18',
       'PCT_UNDR18', 'AGE_18_64', 'PCT_18_64', 'AGE_65OVER', 'PCT_65OVER',
       'ELD_RATIO', 'YTH_RATIO'],
      dtype='object')

In [47]:
serviceAreas_df = serviceAreas_df.groupby('CNTY_FIPS').agg({'AREA_SQMI':'sum', 'POP':'sum', 'POP_CIV':'sum', 'TOTALPOVPOP':'sum',
                                                           'POP100POV':'sum', 'PCT100POV':'mean', 'POP200POV':'sum', 'PCT200POV':'mean', 
                                                           'WHITE':'sum', 'PCT_WHITE':'mean', 'NHS_WHITE':'sum', 'PCT_NHS_WHITE':'mean',
                                                           'BLACK':'sum', 'PCT_BLACK':'mean', 'NHS_BLACK':'sum', 'PCT_NHS_BLACK':'mean', 
                                                           'ASIAN':'sum', 'PCT_ASIAN':'mean', 'NHS_ASIAN':'sum', 'PCT_NHS_ASIAN':'mean',
                                                           'AMIND_ESK':'sum', 'PCT_AMIND_ESK':'mean', 'NHS_AMIND_ESK':'sum', 
                                                           'PCT_NHS_AMIND_ESK':'mean', 'ISLANDER':'sum', 'PCT_ISLAND':'mean', 
                                                           'NHS_ISLANDER':'sum', 'PCT_NHS_ISLANDER':'mean', 'OTHER_RACE':'sum', 'PCT_OTHER':'mean',
                                                           'NHS_OTHER_RACE':'sum', 'PCT_NHS_OTHER_RACE':'mean', 'MULTI_RACE':'sum', 'PCT_MULTI':'mean', 
                                                           'NHS_MULTI_RACE':'sum', 'PCT_NHS_MULTI_RACE':'mean', 'HISPANIC':'sum', 'PCT_HSPNC':'mean', 
                                                           'AGE_UNDER5':'sum', 'PCT_UNDER5':'mean', 'AGE_UNDR18':'sum', 'PCT_UNDR18':'mean', 
                                                           'AGE_18_64':'sum', 'PCT_18_64':'mean', 'AGE_65OVER':'sum', 'PCT_65OVER':'mean',
                                                           'ELD_RATIO':'mean', 'YTH_RATIO':'mean'})

In [48]:
serviceAreas_df.head(15)

,AREA_SQMI,POP,POP_CIV,TOTALPOVPOP,POP100POV,PCT100POV,POP200POV,PCT200POV,WHITE,PCT_WHITE,...,AGE_UNDER5,PCT_UNDER5,AGE_UNDR18,PCT_UNDR18,AGE_18_64,PCT_18_64,AGE_65OVER,PCT_65OVER,ELD_RATIO,YTH_RATIO
CNTY_FIPS,,,,,,,,,,,,,,,,,,,,,
1,743.969228,1206808,1531346,1531346,197191,13.325000,429814,28.508830,694967,46.541643,...,81282,6.029992,337704,21.240104,1013787,66.679802,179855,12.080094,0.217001,0.385723
3,743.187747,1116,1184,1184,179,15.100000,413,34.881757,847,71.537162,...,24,2.388060,217,18.327703,742,62.668919,225,19.003378,0.104895,0.146853
5,605.950377,32435,32932,32932,4277,12.233333,9491,28.384062,30008,91.176489,...,906,3.069782,5645,17.021887,19022,58.176315,8265,24.801798,0.233471,0.444753
7,1677.130966,188610,216592,216592,46643,22.247059,95262,44.699845,181184,83.278962,...,8609,5.031897,44486,20.554329,137376,63.558796,34730,15.886875,0.105989,0.346498
9,1036.927412,40020,44223,44223,5352,12.160000,12278,27.425257,40663,92.084691,...,1554,3.723693,8052,15.952088,25790,57.622278,10381,26.425634,0.179371,0.273023
11,1156.358240,9269,21183,21183,3068,14.420000,9292,44.138519,17278,80.948656,...,1307,6.982084,6088,28.055505,12512,58.628878,2583,13.315617,0.152055,0.744612
13,758.960083,813373,1071795,1071795,114171,10.458454,265705,24.511213,665915,63.222709,...,55388,5.702413,257200,23.071598,673155,62.646906,141440,14.281496,0.282669,0.438375
15,1013.507432,22835,24371,24371,5468,25.000000,11030,49.053897,19201,77.112466,...,1088,5.537899,5778,24.397256,14555,58.738900,4038,16.863844,0.145659,0.551883
17,1734.334273,159054,180066,180066,18497,10.980952,44383,25.382752,157334,88.008197,...,7261,4.221219,38991,20.826540,111703,62.571902,29372,16.601558,0.175361,0.413737
19,6011.049537,462930,931998,931998,255019,27.356281,474424,50.622195,547959,58.842331,...,44064,6.341382,273918,28.538230,560006,59.955660,98074,11.003598,0.140205,0.758371
21,1326.976727,17113,27620,27620,5517,17.950000,12705,43.909051,23615,86.984430,...,1453,7.440304,7549,26.893073,16216,57.924968,3855,15.181959,0.147018,0.560801
23,3583.908172,120936,131318,131318,27325,21.026667,56495,43.150684,108135,81.985334,...,5080,4.730485,25784,19.312929,86690,66.168981,18844,14.518090,0.101328,0.305394
25,4481.373075,32936,166407,166407,38935,23.048387,85889,50.681180,117471,71.774631,...,9596,7.180439,50439,28.643658,96477,57.837333,19491,13.519009,0.194090,0.737863
27,10226.859757,14709,17906,17906,2445,11.900000,5849,29.394198,14936,85.326104,...,778,4.890705,3733,19.895785,10635,59.380827,3538,20.723387,0.404917,0.426003
29,8162.649996,425360,824972,824972,192972,23.104636,396697,47.365389,610504,74.143938,...,46787,6.832469,251231,28.429296,494296,59.115412,79445,10.468538,0.123042,0.739269